const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const script=fs.readFileSync(require('node:path').join(__dirname,'../eet-simulator.js'),'utf8');
const start=script.indexOf('function calculateEETDetails('),end=script.indexOf('// UI 업데이트 로직',start);
const ctx=vm.createContext({});vm.runInContext(script.slice(start,end),ctx);
assert.equal(ctx.calculateEETDetails(24,30,.3,65,'dry_slat').eet,20.2);
assert.equal(ctx.calculateEETDetails(24,30,.3,65,'wet_slat').eet,17.2);
assert.equal(ctx.calculateEETDetails(24,30,0,65,'dry_solid').windChill,0);
assert.equal(ctx.calculateEETDetails(24,30,.15,65,'dry_solid').windChill,0);
assert.equal(ctx.getTargetTemp(120),16);
require('../ventilation.js');const v=globalThis.FarmVentilation.calculateOptimalSettings(100,53.2,323,null,'육성사');
assert.equal(v.volume,11.5*2.2*28);
assert.equal(v.inletArea,5.2);
assert(Math.abs(v.minVel-v.minSuppliedCMH/3600/61.6)<1e-12);
console.log('PASS: supplied EET example, floor changes, wind threshold, target bounds, cross-flow area and unchanged volume.');
